"""Deterministic human-readable rendering of the living prose graph."""

from collections import defaultdict

from perk_dev.prose_map.models import AssemblyLayer, Catalog, RoutedUnit


def _table(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _source_link(unit: RoutedUnit) -> str:
    path = unit.candidate.path
    return f"[`{path}`](../../{path}) · `{unit.candidate.selector}`"


def _layer_text(layer: AssemblyLayer, labels: dict[str, str]) -> str:
    suffix = " _(optional)_" if layer.optional else ""
    if layer.unit is not None:
        label = layer.label or labels.get(layer.unit, layer.unit)
        return f"`{layer.unit}` — {label}{suffix}"
    label = layer.label or str(layer.boundary)
    return f"**Boundary: {layer.boundary}** — {label}{suffix}"


def render_markdown(catalog: Catalog) -> str:
    """Render the catalog without copying source prose into the generated document."""
    graph = catalog.graph
    capabilities = {item.id: item for item in graph.capabilities}
    children: dict[str | None, list[str]] = defaultdict(list)
    for capability in graph.capabilities:
        children[capability.parent].append(capability.id)
    units_by_capability: dict[str, list[RoutedUnit]] = defaultdict(list)
    for unit in catalog.units:
        units_by_capability[unit.capability].append(unit)
    shapes_by_capability = defaultdict(list)
    for shape in graph.session_shapes:
        shapes_by_capability[shape.capability].append(shape)
    assemblies = {assembly.id: assembly for assembly in graph.assemblies}
    labels = {unit.candidate.id: unit.candidate.path for unit in catalog.units}
    consumers: dict[str, list[str]] = defaultdict(list)
    for shape in graph.session_shapes:
        assembly = assemblies.get(shape.assembly)
        if assembly is None:
            continue
        for layer in assembly.layers:
            if layer.unit is not None:
                consumers[layer.unit].append(shape.id)

    lines = [
        "<!-- Generated by `perk-dev prose-map sync`; edit prose-prompt-map.yaml or canonical "
        "sources. -->",
        "# Perk model-facing prose map",
        "",
        "This is the readable projection of perk's living, workflow-first prose graph. It maps "
        "behavior-shaping perk language that reaches a model; it does not reproduce prompt text.",
        "",
        "## Coverage",
        "",
        f"- **{len(catalog.units)}** canonical source units",
        f"- **{sum(len(unit.candidate.fragments) for unit in catalog.units)}** logical fragments",
        f"- **{len(graph.session_shapes)}** session shapes and "
        f"**{len(graph.assemblies)}** assemblies",
        f"- **{len(catalog.excluded)}** explicitly excluded candidates "
        "(policy-only; not displayed)",
        f"- **{len(catalog.findings)}** validation findings",
        "",
        "### Vocabulary",
        "",
        "- **Prose unit:** one canonical model-facing source with stable logical fragments.",
        "- **Session shape:** a cold, warm, headless, ambient, or subagent delivery variant.",
        "- **Prompt assembly:** the ordered perk-owned layers and external boundaries for a shape.",
        "- **Prompt concern:** recurring behavior with one canonical carrier and related units.",
        "",
        "## Capability map",
        "",
    ]

    def render_capability(capability_id: str, level: int) -> None:
        capability = capabilities[capability_id]
        lines.extend([f"{'#' * level} {capability.label}", "", capability.summary, ""])
        units = sorted(
            units_by_capability.get(capability_id, []), key=lambda item: item.candidate.id
        )
        if units:
            lines.extend(
                [
                    "| Unit | Role | Audience | Canonical source | Consumed by |",
                    "| --- | --- | --- | --- | --- |",
                ]
            )
            for unit in units:
                consumed = ", ".join(sorted(set(consumers.get(unit.candidate.id, [])))) or "—"
                lines.append(
                    "| "
                    f"`{_table(unit.candidate.id)}` | `{unit.role}` | `{unit.audience}` | "
                    f"{_source_link(unit)} | {_table(consumed)} |"
                )
            lines.append("")
            lines.extend(["<details>", "<summary>Logical fragments</summary>", ""])
            for unit in units:
                lines.append(f"- `{unit.candidate.id}`")
                for fragment in unit.candidate.fragments:
                    lines.append(f"  - `{fragment.id}` — {fragment.label} (`{fragment.selector}`)")
            lines.extend(["", "</details>", ""])

        shapes = sorted(shapes_by_capability.get(capability_id, []), key=lambda item: item.id)
        if shapes:
            lines.extend([f"{'#' * (level + 1)} Session shapes and assemblies", ""])
            for shape in shapes:
                lines.extend(
                    [
                        f"**{shape.label}** — `{shape.delivery}` via `{shape.trigger}`",
                        "",
                    ]
                )
                assembly = assemblies.get(shape.assembly)
                if assembly is None:
                    lines.extend([f"Missing assembly `{shape.assembly}`.", ""])
                    continue
                for index, layer in enumerate(assembly.layers, start=1):
                    lines.append(f"{index}. {_layer_text(layer, labels)}")
                scenarios = [item for item in graph.scenarios if item.assembly == assembly.id]
                if scenarios:
                    scenario_text = "; ".join(
                        f"`{item.id}` ({'ambient ' if item.include_ambient else ''}"
                        f"{'tools' if item.include_tools else 'no tools'})"
                        for item in scenarios
                    )
                    lines.extend(["", f"Scenarios: {scenario_text}"])
                lines.append("")

        for child_id in children.get(capability_id, []):
            render_capability(child_id, level + 1)

    for root_id in children.get(None, []):
        render_capability(root_id, 2)

    lines.extend(["## Cross-cutting concerns", ""])
    for concern in graph.concerns:
        lines.extend(
            [
                f"### {concern.label}",
                "",
                concern.summary,
                "",
                f"Canonical carrier: `{concern.canonical_unit}`",
                "",
            ]
        )
        for related in concern.related:
            lines.append(f"- `{related.unit}` — {related.relation}")
        lines.append("")

    lines.extend(["## Generated and materialized lineage", ""])
    for lineage in graph.lineage:
        targets = ", ".join(f"`{target}`" for target in lineage.targets)
        lines.append(f"- **{lineage.id}:** `{lineage.source}` {lineage.relationship} {targets}.")
    lines.extend(
        [
            "",
            "## Boundary and exclusion policy",
            "",
            "Pi system text, user messages, borrowed-package prompts, ordinary factual results, "
            "errors, human UI/status copy, arbitrary documentation, and test/pin prose are not "
            "editable prose units. External context appears only as labeled assembly boundaries; "
            "generated copies appear only as lineage targets.",
            "",
        ]
    )
    return "\n".join(lines)
