"""The GitHub gateway — Python plane, **verification-only** (contracts.md §8.4).

A thin ``gh``-shelling gateway implementing the two verification ops the init/doctor
surfaces need in Phase 0. It **never mutates** GitHub (Q9 — the first label is created
lazily by ``/plan-save`` in Phase 1). Mutation ops are named-only in §8.4 and land with
their stage handlers.

The TS extension authors the *same* operation names + payload shapes in Phase 1, so
``doctor`` can verify both planes and either can later swap ``gh``-shell → API-backed.

Issue tier demotion (Objective #252, Node 1.2): the issue-tracking tier functions here
(``create_label`` … ``update_objective_body`` — plan/learn/objective issues, marked comments,
labels) are now the **implementation substrate** of the GitHub issue backend. Production code
must reach the issue tier through the resolver in perk/backends/resolve.py — never by calling
these module functions directly (enforced by the source-scan regression test in
``tests/test_resolve.py``). PR/CI/auth tier functions remain the direct surface for all backends.

This package is the pure GitHub gateway: it never imports the backend tier (the one-way import
guard scans this package for any backend-tier import). The issue human-engagement substrate
(the read-only ``gh api graphql`` comment/description-edit reads) now lives in the backend tier at
perk/backends/github/engagement.py.
"""

from perk.github import _exec
from perk.github._exec import GitHubError
from perk.github.auth import (
    AuthStatus,
    RepoAccess,
    check_auth,
    check_repo_access,
)
from perk.github.objectives import (
    ObjectiveAdoption,
    ObjectiveBodyUpdate,
    ObjectiveHeaderUpdate,
    ObjectiveIssue,
    ObjectiveNodeAdd,
    ObjectiveNodeUpdate,
    ObjectiveState,
    add_objective_node,
    adopt_issue_as_objective,
    create_objective_issue,
    find_objective_issue,
    get_objective,
    update_objective_body,
    update_objective_header,
    update_objective_node,
)
from perk.github.plans import (
    CommentResult,
    IssueRead,
    Label,
    LearnIssueSummary,
    PlanIssue,
    PlanUpdate,
    add_issue_comment,
    add_issue_label,
    close_and_label_consolidated,
    close_issue,
    create_label,
    create_learn_issue,
    create_plan_issue,
    find_learn_issue,
    find_plan_issue,
    list_learn_issues,
    read_issue,
)
from perk.github.prs import (
    PlanAdoption,
    PlanHeaderUpdate,
    PlanState,
    PrBodyUpdate,
    PullRequest,
    adopt_issue_as_plan,
    create_pr,
    default_branch,
    find_comment_id_by_marker,
    find_pr_for_branch,
    get_plan,
    get_plan_body,
    get_pr,
    get_pr_body,
    mark_pr_ready,
    merge_pr,
    prepend_plan_callout,
    update_plan_header,
    update_plan_issue,
    update_pr_body,
    upsert_marked_comment,
    validate_pr_body,
)
from perk.github.reviews import (
    ADD_REVIEW_THREAD_REPLY_MUTATION,
    GET_PR_REVIEW_THREADS_QUERY,
    GET_PR_REVIEWS_QUERY,
    RESOLVE_REVIEW_THREAD_MUTATION,
    BatchResolveResult,
    DiscussionComment,
    InlineReviewComment,
    PrFeedback,
    PrReviewContext,
    Review,
    ReviewComment,
    ReviewPostResult,
    ReviewThread,
    ThreadResolveResult,
    add_pr_reaction,
    get_pr_feedback,
    get_pr_review_context,
    post_pr_review,
    resolve_review_threads,
)
from perk.github.workflows import (
    WorkflowPermissions,
    WorkflowRun,
    cancel_workflow_run,
    get_repo_variable,
    get_workflow_permissions,
    get_workflow_run,
    rerun_workflow_run,
    secret_exists,
    trigger_workflow,
)

__all__ = [
    "ADD_REVIEW_THREAD_REPLY_MUTATION",
    "GET_PR_REVIEWS_QUERY",
    "GET_PR_REVIEW_THREADS_QUERY",
    "RESOLVE_REVIEW_THREAD_MUTATION",
    "AuthStatus",
    "BatchResolveResult",
    "CommentResult",
    "DiscussionComment",
    "GitHubError",
    "InlineReviewComment",
    "IssueRead",
    "Label",
    "LearnIssueSummary",
    "ObjectiveAdoption",
    "ObjectiveBodyUpdate",
    "ObjectiveHeaderUpdate",
    "ObjectiveIssue",
    "ObjectiveNodeAdd",
    "ObjectiveNodeUpdate",
    "ObjectiveState",
    "PlanAdoption",
    "PlanHeaderUpdate",
    "PlanIssue",
    "PlanState",
    "PlanUpdate",
    "PrBodyUpdate",
    "PrFeedback",
    "PrReviewContext",
    "PullRequest",
    "RepoAccess",
    "Review",
    "ReviewComment",
    "ReviewPostResult",
    "ReviewThread",
    "ThreadResolveResult",
    "WorkflowPermissions",
    "WorkflowRun",
    "_exec",
    "add_issue_comment",
    "add_issue_label",
    "add_objective_node",
    "add_pr_reaction",
    "adopt_issue_as_objective",
    "adopt_issue_as_plan",
    "cancel_workflow_run",
    "check_auth",
    "check_repo_access",
    "close_and_label_consolidated",
    "close_issue",
    "create_label",
    "create_learn_issue",
    "create_objective_issue",
    "create_plan_issue",
    "create_pr",
    "default_branch",
    "find_comment_id_by_marker",
    "find_learn_issue",
    "find_objective_issue",
    "find_plan_issue",
    "find_pr_for_branch",
    "get_objective",
    "get_plan",
    "get_plan_body",
    "get_pr",
    "get_pr_body",
    "get_pr_feedback",
    "get_pr_review_context",
    "get_repo_variable",
    "get_workflow_permissions",
    "get_workflow_run",
    "list_learn_issues",
    "mark_pr_ready",
    "merge_pr",
    "post_pr_review",
    "prepend_plan_callout",
    "read_issue",
    "rerun_workflow_run",
    "resolve_review_threads",
    "secret_exists",
    "trigger_workflow",
    "update_objective_body",
    "update_objective_header",
    "update_objective_node",
    "update_plan_header",
    "update_plan_issue",
    "update_pr_body",
    "upsert_marked_comment",
    "validate_pr_body",
]
