"""The compact public delivery façade and temporarily retained operation exports.

The canonical read surface is the repository-scoped :class:`Delivery` status slice with three
nominal aggregate authorities. Pure train projection, production observation adapters, and
compatibility readers are internal modules. Existing journal, authoring, continuation, layer,
publication, synchronization, finalization, and landing exports remain temporarily public while
their operation families migrate onto the façade; no unimplemented operation methods are implied.
"""

from perk.delivery.capability import (
    CapabilityCheck,
    CapabilityReport,
    preflight_stacked_authoring,
    probe_atomic_push_urls,
)
from perk.delivery.continuation import (
    ContinuationLayer,
    ContinuationManifest,
    PendingContinuation,
    continuations_dir,
    manifest_path,
    pending_continuation,
    write_manifest,
)
from perk.delivery.facade import (
    Delivery,
    DeliveryError,
    DeliveryGit,
    DeliveryGitHub,
    DeliveryPersistence,
    StatusRequest,
    StatusResult,
)
from perk.delivery.finalize import (
    LandedPlan,
    LandFinalization,
    LearnConsumeUpdate,
    ObjectiveLandUpdate,
    finalize_landed_plan,
)
from perk.delivery.journal import (
    JOURNAL_EVENT_MAX_CHARS,
    JOURNAL_SCHEMA_VERSION,
    EventRole,
    JournalCorruptionError,
    JournalEvent,
    JournalFold,
    JournalRecordTooLarge,
    OperationKind,
    OperationState,
    OutcomeRecord,
    PreparedRecord,
    canonical_payload,
    ensure_event_size,
    fold_events,
    mint_operation_id,
    parse_journal_comment,
    render_event,
)
from perk.delivery.land import (
    CheckView,
    LandDisposition,
    LandLayerReadiness,
    LandObservationError,
    LandObservations,
    LandPlan,
    LandPlanLayer,
    LandReadiness,
    MergeRulesView,
    PrLandView,
    assess_land_readiness,
)
from perk.delivery.landing import (
    LandedLayer,
    LandError,
    LandOutcome,
    land_train,
    squash_commit_message,
)
from perk.delivery.layer import (
    LayerContext,
    LayerContextOut,
    LayerError,
    PreparedLayerStart,
    derive_layer_context,
    prepare_layer_start,
    require_ready_layer,
    require_reviewable_layer,
)
from perk.delivery.observe import GatewayLandObservations, resolve_delivery
from perk.delivery.persistence import (
    AppendResult,
    JournalAppendAmbiguous,
    TrainPersistence,
    TrainPersistenceError,
    UnresolvedOperationError,
    resolve_train_persistence,
)
from perk.delivery.publish import (
    DeliveryOperationFacts,
    LayerBodyFacts,
    PublicationError,
    PublicationResult,
    TrainRowFacts,
    publish_layer,
)
from perk.delivery.sync import (
    ClaimedLayer,
    SyncCascade,
    SyncedLayer,
    SyncError,
    SyncResult,
    derive_claimed_prefix,
    synchronize_train,
)
from perk.delivery.writers import RemoteWriterProbe, WriterObservationError

__all__ = [
    "JOURNAL_EVENT_MAX_CHARS",
    "JOURNAL_SCHEMA_VERSION",
    "AppendResult",
    "CapabilityCheck",
    "CapabilityReport",
    "CheckView",
    "ClaimedLayer",
    "ContinuationLayer",
    "ContinuationManifest",
    "Delivery",
    "DeliveryError",
    "DeliveryGit",
    "DeliveryGitHub",
    "DeliveryOperationFacts",
    "DeliveryPersistence",
    "EventRole",
    "GatewayLandObservations",
    "JournalAppendAmbiguous",
    "JournalCorruptionError",
    "JournalEvent",
    "JournalFold",
    "JournalRecordTooLarge",
    "LandDisposition",
    "LandError",
    "LandFinalization",
    "LandLayerReadiness",
    "LandObservationError",
    "LandObservations",
    "LandOutcome",
    "LandPlan",
    "LandPlanLayer",
    "LandReadiness",
    "LandedLayer",
    "LandedPlan",
    "LayerBodyFacts",
    "LayerContext",
    "LayerContextOut",
    "LayerError",
    "LearnConsumeUpdate",
    "MergeRulesView",
    "ObjectiveLandUpdate",
    "OperationKind",
    "OperationState",
    "OutcomeRecord",
    "PendingContinuation",
    "PrLandView",
    "PreparedLayerStart",
    "PreparedRecord",
    "PublicationError",
    "PublicationResult",
    "RemoteWriterProbe",
    "StatusRequest",
    "StatusResult",
    "SyncCascade",
    "SyncError",
    "SyncResult",
    "SyncedLayer",
    "TrainPersistence",
    "TrainPersistenceError",
    "TrainRowFacts",
    "UnresolvedOperationError",
    "WriterObservationError",
    "assess_land_readiness",
    "canonical_payload",
    "continuations_dir",
    "derive_claimed_prefix",
    "derive_layer_context",
    "ensure_event_size",
    "finalize_landed_plan",
    "fold_events",
    "land_train",
    "manifest_path",
    "mint_operation_id",
    "parse_journal_comment",
    "pending_continuation",
    "preflight_stacked_authoring",
    "prepare_layer_start",
    "probe_atomic_push_urls",
    "publish_layer",
    "render_event",
    "require_ready_layer",
    "require_reviewable_layer",
    "resolve_delivery",
    "resolve_train_persistence",
    "squash_commit_message",
    "synchronize_train",
    "write_manifest",
]
