"""The compact public delivery façade and retained operation exports.

The canonical surface is the repository-scoped :class:`Delivery` status plus flat Prepare family
over three nominal aggregate authorities. Pure train projection, layer context/core, private
capability rows, production adapters, and compatibility readers are internal modules. Existing
journal, continuation, publication, synchronization, finalization, and landing exports remain
public while their operation families migrate; ``probe_atomic_push_urls`` is retained only for
the deferred sync owner.
"""

from perk.delivery.facade import (
    Delivery,
    DeliveryError,
    DeliveryGit,
    DeliveryGitHub,
    DeliveryPersistence,
    PrepareRequest,
    PrepareResult,
    StatusRequest,
    StatusResult,
    SyncRequest,
    SyncResult,
)
from perk.delivery.finalize import (
    LandedPlan,
    LandFinalization,
    LearnConsumeUpdate,
    ObjectiveLandUpdate,
    finalize_landed_plan,
)
from perk.delivery.journal import (
    JOURNAL_EVENT_MAX_CHARS,
    JOURNAL_SCHEMA_VERSION,
    EventRole,
    JournalCorruptionError,
    JournalEvent,
    JournalFold,
    JournalRecordTooLarge,
    OperationKind,
    OperationState,
    OutcomeRecord,
    PreparedRecord,
    canonical_payload,
    ensure_event_size,
    fold_events,
    mint_operation_id,
    parse_journal_comment,
    render_event,
)
from perk.delivery.land import (
    CheckView,
    LandDisposition,
    LandLayerReadiness,
    LandObservationError,
    LandObservations,
    LandPlan,
    LandPlanLayer,
    LandReadiness,
    MergeRulesView,
    PrLandView,
    assess_land_readiness,
)
from perk.delivery.landing import (
    LandedLayer,
    LandError,
    LandOutcome,
    land_train,
    squash_commit_message,
)
from perk.delivery.observe import GatewayLandObservations, resolve_delivery
from perk.delivery.persistence import (
    AppendResult,
    JournalAppendAmbiguous,
    TrainPersistence,
    TrainPersistenceError,
    UnresolvedOperationError,
    resolve_train_persistence,
)
from perk.delivery.publish import (
    DeliveryOperationFacts,
    LayerBodyFacts,
    PublicationError,
    PublicationResult,
    TrainRowFacts,
    publish_layer,
)

__all__ = [
    "JOURNAL_EVENT_MAX_CHARS",
    "JOURNAL_SCHEMA_VERSION",
    "AppendResult",
    "CheckView",
    "Delivery",
    "DeliveryError",
    "DeliveryGit",
    "DeliveryGitHub",
    "DeliveryOperationFacts",
    "DeliveryPersistence",
    "EventRole",
    "GatewayLandObservations",
    "JournalAppendAmbiguous",
    "JournalCorruptionError",
    "JournalEvent",
    "JournalFold",
    "JournalRecordTooLarge",
    "LandDisposition",
    "LandError",
    "LandFinalization",
    "LandLayerReadiness",
    "LandObservationError",
    "LandObservations",
    "LandOutcome",
    "LandPlan",
    "LandPlanLayer",
    "LandReadiness",
    "LandedLayer",
    "LandedPlan",
    "LayerBodyFacts",
    "LearnConsumeUpdate",
    "MergeRulesView",
    "ObjectiveLandUpdate",
    "OperationKind",
    "OperationState",
    "OutcomeRecord",
    "PrLandView",
    "PrepareRequest",
    "PrepareResult",
    "PreparedRecord",
    "PublicationError",
    "PublicationResult",
    "StatusRequest",
    "StatusResult",
    "SyncRequest",
    "SyncResult",
    "TrainPersistence",
    "TrainPersistenceError",
    "TrainRowFacts",
    "UnresolvedOperationError",
    "assess_land_readiness",
    "canonical_payload",
    "ensure_event_size",
    "finalize_landed_plan",
    "fold_events",
    "land_train",
    "mint_operation_id",
    "parse_journal_comment",
    "publish_layer",
    "render_event",
    "resolve_delivery",
    "resolve_train_persistence",
    "squash_commit_message",
]
