"""Execute deferred land operations from activation script.

This exec command performs the actual merge and cleanup operations for landing a PR.
It is called by the activation script after the user has approved the operation.

Usage:
    erk exec land-execute --pr-number=123 --branch=foo [options]

All validation happens during the validation phase (erk land). This command
executes the pre-validated operations.

Exit Codes:
    0: Success (PR merged, branch deleted)
    1: Error (merge failed, validation error)
"""

from pathlib import Path

import click

from erk.cli.commands.land_cmd import _execute_land
from erk.cli.commands.objective_helpers import run_objective_update_after_land
from erk_shared.context.helpers import require_context


@click.command(name="land-execute")
@click.option(
    "--pr-number",
    type=int,
    required=True,
    help="PR number to merge",
)
@click.option(
    "--branch",
    required=True,
    help="Branch name being landed",
)
@click.option(
    "--worktree-path",
    type=click.Path(),
    help="Path to worktree being cleaned up",
)
@click.option(
    "--is-current-branch",
    is_flag=True,
    help="Whether landing from the branch's own worktree",
)
@click.option(
    "--target-child",
    help="Target child branch for --up navigation",
)
@click.option(
    "--objective-number",
    type=int,
    help="Linked objective issue number",
)
@click.option(
    "--linked-pr-number",
    "learn_source_pr",
    type=int,
    help="PR number that the learn issue will be created for",
)
@click.option(
    "--use-graphite",
    is_flag=True,
    help="Use Graphite for merge",
)
@click.option(
    "--pull/--no-pull",
    "pull_flag",
    default=True,
    help="Pull latest changes after landing (default: --pull)",
)
@click.option(
    "--no-delete",
    is_flag=True,
    help="Preserve the local branch and its slot assignment after landing",
)
@click.option(
    "--no-cleanup",
    is_flag=True,
    help="User declined cleanup during validation phase",
)
@click.option(
    "--skip-learn",
    "skip_learn",
    is_flag=True,
    help="Skip creating a learn PR",
)
@click.option(
    "--script",
    is_flag=True,
    help="Output activation script path (for shell integration)",
)
@click.option(
    "--up",
    "up_flag",
    is_flag=True,
    help="Navigate upstack to child branch after landing (resolves child at execution time)",
)
@click.option(
    "-f",
    "--force",
    "force_flag",
    is_flag=True,
    help="Accept flag for compatibility (execute mode always skips confirmations)",
)
@click.option(
    "--down",
    "down_flag",
    is_flag=True,
    help="Accept flag for compatibility (navigate-to-trunk is the default when --up is not passed)",
)
@click.pass_context
def land_execute(
    ctx: click.Context,
    *,
    pr_number: int,
    branch: str,
    worktree_path: str | None,
    is_current_branch: bool,
    target_child: str | None,
    objective_number: int | None,
    learn_source_pr: int | None,
    use_graphite: bool,
    skip_learn: bool,
    pull_flag: bool,
    no_delete: bool,
    no_cleanup: bool,
    script: bool,
    up_flag: bool,
    force_flag: bool,
    down_flag: bool,
) -> None:
    """Execute deferred land operations.

    This command is called by the activation script generated by `erk land`.
    All validation has already been performed - this just executes the
    merge and cleanup operations.

    Confirmations are skipped because the user already approved by sourcing
    the activation script.

    The --up flag resolves the target child branch at execution time (rather than
    baking it into the script at validation time). This allows the user to change
    their stack between validation and execution.
    """
    erk_ctx = require_context(ctx)

    # Resolve --up to target child branch at execution time
    resolved_target_child = target_child
    repo_root = erk_ctx.git.repo.get_repository_root(erk_ctx.cwd)

    # Compute main repo root BEFORE execution pipeline deletes the worktree.
    # get_git_common_dir() returns the shared .git dir even from a worktree,
    # so .parent gives the main repo root that always exists after cleanup.
    common_dir = erk_ctx.git.repo.get_git_common_dir(erk_ctx.cwd)
    main_repo_root = common_dir.parent if common_dir is not None else repo_root
    if up_flag and target_child is None:
        children = erk_ctx.branch_manager.get_child_branches(repo_root, branch)
        if not children:
            raise click.ClickException(f"Cannot use --up: branch '{branch}' has no children")
        if len(children) > 1:
            children_str = ", ".join(f"'{c}'" for c in children)
            raise click.ClickException(
                f"Cannot use --up: branch '{branch}' has multiple children: {children_str}"
            )
        resolved_target_child = children[0]

    # _execute_land may raise SystemExit(0) after successful merge+cleanup.
    # We catch it to run the objective update before re-raising.
    exit_after: SystemExit | None = None
    try:
        _execute_land(
            erk_ctx,
            pr_number=pr_number,
            branch=branch,
            worktree_path=Path(worktree_path) if worktree_path else None,
            is_current_branch=is_current_branch,
            target_child_branch=resolved_target_child,
            use_graphite=use_graphite,
            pull_flag=pull_flag,
            no_delete=no_delete,
            no_cleanup=no_cleanup,
            script=script,
            learn_source_pr=learn_source_pr,
            skip_learn=skip_learn,
        )
    except SystemExit as exc:
        if exc.code != 0:
            raise
        exit_after = exc

    # Objective update (fail-open — merge already succeeded)
    if objective_number is not None:
        run_objective_update_after_land(
            erk_ctx,
            objective=objective_number,
            pr=pr_number,
            branch=branch,
            worktree_path=main_repo_root,
        )

    if exit_after is not None:
        raise exit_after
